---
title: Reflecting on Christmas dinner
author: ''
date: '2018-12-29'
slug: reflecting-on-christmas-dinner
categories: []
tags:
  - Personal
  - Recipes
description: Reflections on making 2018 Christmas dinner
hacker_news_id: ''
lobsters_id: ''
meta_img: /images/image.jpg
---

A sign of getting older is when visiting home for the holidays is more stressful than not. With every year that passes, a responsibility gets added to my plate. And with this year, both the metaphorical and literal plate as preparing Christmas dinner became one of the layered responsibilities. 

And like all great heroes, I didn't ask for this responsibility; it was simply bestowed upon me against my will. 

I mourn for a time when the holidays were about predicting what gifts I'd receive, and my biggest worry was whether or not I'd be expected to share my gifts with my sister. Holidays are now about headcount and logistics planning. The best Christmas gift you can hope for is that everyone shows up on time, and preferably sober. 

If you're like me and put many things to last minute, you'll find that grocery shopping on Christmas eve is a depressing event akin to Black Friday shopping, except everything you buy is meant for the consumption and enjoyment of others. Everyone shopping is in a state of panic and distress, desperately hoping to cross off the remaining items on their grocery lists, the shelves are barren, the produce in disarray, and good luck trying to find a store clerk available and willing to help. 

Nonetheless, I found it somewhat touching to be trusted with deciding my family's Christmas dinner. I guess that's what desperation will do to a family. 

**2018 Carey family Christmas menu:**  

 * Mixed salad
 * Roasted root vegetables (recipe from [NYT Cooking](https://cooking.nytimes.com/recipes/1016559-roasted-carrots-and-parsnips-with-rosemary-and-garlic?action=click&module=Global%20Search%20Recipe%20Card&pgType=search&rank=2))
 * Mashed potatoes
 * Beef tenderloin with horseradish crème fraîche sauce (recipe from [Serious Eats](https://www.seriouseats.com/recipes/2014/12/slow-roasted-beef-tenderloin-recipe.html)  \)
 * Apple crisp (recipe from [NYT cooking](https://cooking.nytimes.com/recipes/11752-mark-bittmans-apple-crisp))

*** 

## Notes on the menu items

### Rooted vegetables
 * Add quartered red onions to the root vegetables
 * Coring parsnips is nonsense, disregard those instructions
 
### Beef tenderloin
 * Use the [horseradish crème fraîche recipe](https://cooking.nytimes.com/recipes/1018533-horseradish-creme-fraiche-sauce) from NYT cooking, it's less effort than Serious Eats
 * Horseradish is impossible to find on Christmas Eve, but ginger makes a great substitute! 
 * Use an instant read thermometer to cook the beef to your liking (I bought a [Thermapen MK4](https://www.thermoworks.com/Thermapen-Mk4) for next year)
 
### Apple crisp
 * Use the recipe from the NYT comments section for the crumble of the Apple Crisp: 2/3 brown (not white) sugar, 1/2 cup flour, 1/2 cup rolled oats.
 * Crisps are so much easier than pie and equally tasty
 
 
